### ISSUE TITLE
Setting device based on local rank is not robust

### ISSUE THREAD

**Issue by awgu** [pytorch/torchtitan#423]
Run command:
```
CUDA_VISIBLE_DEVICES=2,3 CONFIG_FILE=train_configs/llama3_8b.toml ./run_llama_train.sh 
```

Stack trace:
```
traceback : Traceback (most recent call last):
    File "/data/users/andgu/pytorch/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
      return f(*args, **kwargs)
    File "/data/users/andgu/torchtrain/train.py", line 162, in main
      torch.cuda.set_device(device)
    File "/data/users/andgu/pytorch/torch/cuda/__init__.py", line 470, in set_device
      torch._C._cuda_setDevice(device)
  RuntimeError: CUDA error: invalid device ordinal
  CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
  For debugging consider passing CUDA_LAUNCH_BLOCKING=1
  Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Code pointer:
https://github.com/pytorch/torchtitan/blob/abb9e1533d7ab505768fe000e5152cd561a0229d/train.py#L161-L162

Calling `torch.cuda.set_device(local_rank)` is not robust such as when we use `CUDA_VISIBLE_DEVICES` to use an assignment different from rank `i` <-> `cuda:i`.

**Comment by awgu** [comment]
Nevermind. This was my own issue. I need `NGPU=2` before the run command.
