### ISSUE TITLE
FSDP2 mixed precision error

### ISSUE THREAD

**Issue by jiagaoxiang** [pytorch/torchtitan#671]
I specified mixed precision as
```python
        mp_policy = MixedPrecisionPolicy(
                param_dtype=torch.bfloat16,
                reduce_dtype=torch.bfloat16,
                # output_dtype=get_dtype(args),
            )

```

But got the error:

```
[rank2]: Traceback (most recent call last):                                                                                                                            
[rank2]:   File "/home/amd/benchmark/train_fsdp2.py", line 419, in <module>                                                                                            
[rank2]:     main()                                                                                                                                                    
[rank2]:   File "/home/amd/benchmark/train_fsdp2.py", line 415, in main                                                                                                
[rank2]:     train(trainer_state, args)                                                                                                                                
[rank2]:   File "/home/amd/benchmark/train_fsdp2.py", line 335, in train                                                                                               
[rank2]:     loss.backward()                                                                                                                                           
[rank2]:   File "/usr/local/lib/python3.11/dist-packages/torch/_tensor.py", line 581, in backward                                                                      
[rank2]:     torch.autograd.backward(                                                                                                                                  
[rank2]:   File "/usr/local/lib/python3.11/dist-packages/torch/autograd/__init__.py", line 347, in backward                                                            
[rank2]:     _engine_run_backward(                                                                                                                                     
[rank2]:   File "/usr/local/lib/python3.11/dist-packages/torch/autograd/graph.py", line 825, in _engine_run_backward                                                   
[rank2]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                                     
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                     
[rank2]: RuntimeError: Expected running_mean to have type BFloat16 but got Float   
```

Anyone know what's happening here?

here are the version info (I am using AMD GPU):

pytorch-triton-rocm     3.1.0
torch                   2.5.1+rocm6.2
torchaudio              2.5.1+rocm6.2
torchvision             0.20.1+rocm6.2

**Comment by awgu** [comment]
Is this using batch norm?

**Comment by jiagaoxiang** [comment]
> Is this using batch norm?

@awgu It uses both batch norm and layer norm as it uses both image encoder and text encoder.

**Comment by awgu** [comment]
I think this error is coming from the batch norm backward. Since FSDP2 does not support buffer dtype, you need to handle the casting of buffers to bf16 yourself.

```
for module in model.modules():
    for buffer_name, buffer in module.named_buffers(recurse=False):
        setattr(module, buffer_name, buffer.to(torch.bfloat16))
```
